-wget hosts: all
  connection: local
  gather_facts: no
  sudo: no
  vars_files:
    - vars.yml
  tasks:
    - name: add 'tap' repository
      homebrew_tap:
        name: "{{ item }}"
        state: present
      with_items: "{{ homebrew_taps }}"

    - name: update Homebrew
      homebrew:
        update_homebrew: yes

    - name: install packages
      homebrew:
        name: "{{ item.name }}"
        state: "{{ item.state | default('latest') }}"
        install_options: "{{
          item.install_options | default() | join(',')
          if item.install_options is not string
          else item.install_options
        }}"
      with_items: "{{ homebrew_packages }}"
      register: brew_result

    - name: mkdir 'brew_info'
      file:
        path: brew_info
        state: directory

    - name: save `brew info` to 'brew_info' directory
      shell: "brew info {{ item }} > brew_info/{{ item }}"
      with_items: "{{ brew_result.results | selectattr('changed') | map(attribute='item') | map(attribute='name') | list }}"

